services:
    bookmark-page:
        image: gemini2350/bookmark-page:latest
        ports:
            - "8080:80"
        volumes:
            - db-data:/var/lib/mysql
        restart: unless-stopped
volumes:
    db-data:
